import { useState, useEffect } from "react"
import ReactMarkdown from "react-markdown"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { FileText, Download, Clock, CheckCircle, User, Calendar, MapPin, AlertTriangle } from "lucide-react"
import type { EOPReport } from "@/types"

const priorityColors = {
  low: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300",
  medium: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-300", 
  high: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300"
}

const categoryColors = {
  preparation: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300",
  response: "bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-300",
  recovery: "bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-300",
  mitigation: "bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-300"
}

const statusColors = {
  pending: "bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-300",
  in_progress: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300",
  completed: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300"
}

export default function ReportDisplayPage() {
  const [report, setReport] = useState<EOPReport | null>(null)

  useEffect(() => {
    // Get the final report from sessionStorage
    const storedReport = sessionStorage.getItem('finalEOPReport')
    if (storedReport) {
      const parsedReport = JSON.parse(storedReport) as EOPReport
      setReport(parsedReport)
    }
  }, [])

  const handleDownloadReport = () => {
    if (!report) return

    const content = `# ${report.title}

Generated at: ${new Date(report.generatedAt).toLocaleString()}
Status: ${report.status}

## Disaster Information
- Type: ${report.disasterInfo.disasterType}
- Affected Area: ${report.disasterInfo.affectedArea}
- Severity: ${report.disasterInfo.severityLevel}
- Period: ${report.disasterInfo.dateFrom} to ${report.disasterInfo.dateTo}

---

${report.content}

## Tasks Summary

| Task | Priority | Category | Assigned To | Deadline | Status |
|------|----------|----------|-------------|-----------|--------|
${report.tasks.map(task => 
  `| ${task.title} | ${task.priority} | ${task.category} | ${task.assignedTo} | ${new Date(task.deadline).toLocaleDateString()} | ${task.status} |`
).join('\n')}

---
Report generated by Emergency Response System
`

    const blob = new Blob([content], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `EOP-Report-${report.id}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  if (!report) {
    return (
      <div className="container mx-auto p-6 max-w-4xl">
        <div className="text-center py-12">
          <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-4">
            No Report Found
          </h1>
          <p className="text-gray-600 dark:text-gray-400 mb-6">
            Please generate and confirm an EOP report first.
          </p>
          <Button onClick={() => window.location.href = '/eop/create'}>
            Generate New Report
          </Button>
        </div>
      </div>
    )
  }

  return (
    <div className="container mx-auto p-6 max-w-6xl">
      {/* Header */}
      <div className="mb-6">
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-100">
              Emergency Operation Plan Report
            </h1>
            <p className="text-gray-600 dark:text-gray-400 mt-2">
              Final confirmed EOP ready for implementation
            </p>
          </div>
          <div className="flex gap-3">
            <Button 
              variant="outline" 
              onClick={handleDownloadReport}
              className="flex items-center gap-2"
            >
              <Download className="h-4 w-4" />
              Download Report
            </Button>
            <Badge variant="default" className="flex items-center gap-1 px-3 py-1">
              <CheckCircle className="h-4 w-4" />
              Confirmed
            </Badge>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* Report Info Sidebar */}
        <div className="lg:col-span-1 space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5" />
                Report Info
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <div className="text-sm font-medium text-gray-500 dark:text-gray-400">Report ID</div>
                <div className="text-sm font-mono">{report.id}</div>
              </div>
              
              <div className="flex items-center gap-2">
                <Clock className="h-4 w-4 text-gray-500 dark:text-gray-400" />
                <div>
                  <div className="text-sm font-medium text-gray-500 dark:text-gray-400">Generated</div>
                  <div className="text-sm">{new Date(report.generatedAt).toLocaleString()}</div>
                </div>
              </div>

              <Separator />

              <div className="space-y-3">
                <h4 className="text-sm font-medium">Disaster Details</h4>
                
                <div className="flex items-center gap-2">
                  <AlertTriangle className="h-4 w-4 text-orange-500" />
                  <div>
                    <div className="text-sm font-medium">Type</div>
                    <div className="text-sm text-gray-600 dark:text-gray-400 capitalize">
                      {report.disasterInfo.disasterType}
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <MapPin className="h-4 w-4 text-blue-500" />
                  <div>
                    <div className="text-sm font-medium">Area</div>
                    <div className="text-sm text-gray-600 dark:text-gray-400">
                      {report.disasterInfo.affectedArea}
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <Calendar className="h-4 w-4 text-purple-500" />
                  <div>
                    <div className="text-sm font-medium">Period</div>
                    <div className="text-sm text-gray-600 dark:text-gray-400">
                      {new Date(report.disasterInfo.dateFrom).toLocaleDateString()} - {new Date(report.disasterInfo.dateTo).toLocaleDateString()}
                    </div>
                  </div>
                </div>

                <div>
                  <div className="text-sm font-medium">Severity</div>
                  <Badge variant="secondary" className="capitalize">
                    {report.disasterInfo.severityLevel}
                  </Badge>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <User className="h-5 w-5" />
                Task Summary
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span>Total Tasks</span>
                  <span className="font-medium">{report.tasks.length}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span>High Priority</span>
                  <span className="font-medium text-red-600">
                    {report.tasks.filter(t => t.priority === 'high').length}
                  </span>
                </div>
                <div className="flex justify-between text-sm">
                  <span>Response Tasks</span>
                  <span className="font-medium">
                    {report.tasks.filter(t => t.category === 'response').length}
                  </span>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Main Content */}
        <div className="lg:col-span-3 space-y-6">
          {/* Report Content */}
          <Card>
            <CardHeader>
              <CardTitle>Emergency Operation Plan</CardTitle>
              <CardDescription>
                Generated report content based on disaster information and AI recommendations
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="prose dark:prose-invert max-w-none">
                <ReactMarkdown>{report.content}</ReactMarkdown>
              </div>
            </CardContent>
          </Card>

          {/* Tasks Table */}
          <Card>
            <CardHeader>
              <CardTitle>Implementation Tasks</CardTitle>
              <CardDescription>
                Generated tasks for EOP implementation with priorities and assignments
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Task</TableHead>
                    <TableHead>Priority</TableHead>
                    <TableHead>Category</TableHead>
                    <TableHead>Assigned To</TableHead>
                    <TableHead>Deadline</TableHead>
                    <TableHead>Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {report.tasks.map((task) => (
                    <TableRow key={task.id}>
                      <TableCell>
                        <div>
                          <div className="font-medium">{task.title}</div>
                          <div className="text-sm text-gray-600 dark:text-gray-400 mt-1">
                            {task.description}
                          </div>
                        </div>
                      </TableCell>
                      <TableCell>
                        <Badge className={`${priorityColors[task.priority]} capitalize`}>
                          {task.priority}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <Badge className={`${categoryColors[task.category]} capitalize`}>
                          {task.category}
                        </Badge>
                      </TableCell>
                      <TableCell>{task.assignedTo}</TableCell>
                      <TableCell>{new Date(task.deadline).toLocaleString()}</TableCell>
                      <TableCell>
                        <Badge className={`${statusColors[task.status]} capitalize`}>
                          {task.status.replace('_', ' ')}
                        </Badge>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}